<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude('var')
    ->exclude('tests/_support/_generated');

return (new PhpCsFixer\Config())
    ->setRules([
                   'no_whitespace_before_comma_in_array' => true,
                   'trailing_comma_in_multiline' => true,
                   'no_trailing_comma_in_singleline_array' => true,
                   'array_syntax' => ['syntax' => 'short'],
                   'trim_array_spaces' => true,
                   'lowercase_keywords' => true,
                   'constant_case' => true,
                   'braces' => [
                       'allow_single_line_anonymous_class_with_empty_body' => false,
                       'allow_single_line_closure' => false,
                       'position_after_functions_and_oop_constructs' => 'next',
                       'position_after_control_structures' => 'same',
                       'position_after_anonymous_constructs' => 'same',
                   ],
                   'lowercase_static_reference' => true,
                   'magic_constant_casing' => true,
                   'magic_method_casing' => true,
                   'native_function_casing' => true,
                   'native_function_type_declaration_casing' => true,
                   'lowercase_cast' => true,
                   'class_attributes_separation' => [
                       'elements' => [
                           'const' => 'one',
                           'method' => 'one',
                           'property' => 'one',
                           'trait_import' => 'one',
                       ],
                   ],
                   'class_definition' => [
                       'multi_line_extends_each_single_line' => false,
                       'single_item_single_line' => false,
                       'single_line' => false,
                       'space_before_parenthesis' => false,
                   ],
                   'self_static_accessor' => true,
                   'visibility_required' => [
                       'elements' => [
                           'property',
                           'method',
                           'const',
                       ],
                   ],
                   'protected_to_private' => true,
                   'no_unneeded_final_method' => true,
                   'no_blank_lines_after_class_opening' => true,
                   'switch_case_space' => true,
                   'switch_case_semicolon_to_colon' => true,
                   'simplified_if_return' => true,
                   'no_useless_else' => true,
                   'include' => true,
                   'elseif' => true,
                   'function_declaration' => ['closure_function_spacing' => 'one'],
                   'function_typehint_space' => true,
                   'method_argument_space' => [
                       'keep_multiple_spaces_after_comma' => false,
                       'on_multiline' => 'ensure_fully_multiline',
                       'after_heredoc' => false,
                   ],
                   'no_spaces_after_function_name' => true,
                   'phpdoc_to_property_type' => true,
                   'phpdoc_to_param_type' => true,
                   'phpdoc_to_return_type' => true,
                   'return_type_declaration' => true,
                   'void_return' => true,
                   'fully_qualified_strict_types' => true,
                   'no_unused_imports' => true,
                   'ordered_imports' => true,
                   'single_import_per_statement' => true,
                   'single_line_after_imports' => true,
                   'combine_consecutive_issets' => true,
                   'single_space_after_construct' => true,
                   'blank_line_after_namespace' => true,
                   'clean_namespace' => true,
                   'no_leading_namespace_whitespace' => true,
                   'single_blank_line_before_namespace' => true,
                   'standardize_increment' => true,
                   'object_operator_without_whitespace' => true,
                   'new_with_braces' => true,
                   'logical_operators' => true,
                   'concat_space' => ['spacing' => 'one'],
                   'binary_operator_spaces' => ['default' => 'single_space'],
                   'unary_operator_spaces' => true,
                   'ternary_operator_spaces' => true,
                   'standardize_not_equals' => true,
                   'blank_line_after_opening_tag' => true,
                   'full_opening_tag' => true,
                   'linebreak_after_opening_tag' => true,
                   'no_closing_tag' => true,
                   'php_unit_construct' => true,
                   'php_unit_method_casing' => ['case' => 'camel_case'],
                   'php_unit_strict' => true,
                   'simplified_null_return' => true,
                   'no_empty_statement' => true,
                   'no_singleline_whitespace_before_semicolons' => true,
                   'semicolon_after_instruction' => true,
                   'declare_strict_types' => true,
                   'single_quote' => true,
                   'no_whitespace_in_blank_line' => true,
                   'no_spaces_inside_parenthesis' => true,
                   'no_spaces_around_offset' => ['positions' => ['inside', 'outside']],
                   'no_extra_blank_lines' => true,
                   'method_chaining_indentation' => true,
                   'compact_nullable_typehint' => true,
                   'blank_line_before_statement' => true,
                   'array_indentation' => true,
                   'align_multiline_comment' => ['comment_type' => 'phpdocs_only'],
                   'no_blank_lines_after_phpdoc' => true,
                   'no_empty_phpdoc' => true,
                   'phpdoc_align' => ['align' => 'left'],
                   'phpdoc_annotation_without_dot' => true,
                   'phpdoc_indent' => true,
                   'phpdoc_trim_consecutive_blank_line_separation' => true,
                   'phpdoc_trim' => true,
                   'phpdoc_types' => ['groups' => ['simple', 'alias', 'meta']],
                   'phpdoc_var_annotation_correct_order' => true,
                   'single_blank_line_at_eof' => true,
               ])
    ->setFinder($finder);
